export const WRONG_EMAIL_PASSWORD = 'The username or password you entered did not match our records.';
export const EMAIL_EXIST = 'Email is already used by another user.';
export const REGISTERED = 'You are registered successfully.';
export const INVALID_JWT = 'Invalid JWT';
export const EXPIRED_JWT = 'Expired JWT';
export const INVALID_REFRESH_TOKEN = 'Invalid refresh token';
export const NOT_FOUND_USER = 'Cannot find user';
export const NOT_ALLOWED_MODIFY = 'You are not allowed to modify the data';
export const NOT_ALLOWED_DELETE = 'You are not allowed to remove the data';
